### ISSUE TITLE
[ADAP-517] [Bug] `latest` and `1.x.latest` tags for ghcr Docker releases are stale

### ISSUE THREAD

**Issue by scotthenley** [dbt-labs/dbt-snowflake#597]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Look at https://github.com/dbt-labs/dbt-snowflake/pkgs/container/dbt-snowflake/versions?filters%5Bversion_type%5D=tagged

1.3.0 container image is still tagged as "latest":

<img width="274" alt="image" src="https://github.com/dbt-labs/dbt-snowflake/assets/44704949/8a9720db-cda1-413b-9aad-26261d9221df">

### Expected Behavior

The most recent stable image version should be tagged as "latest" 

### Steps To Reproduce

1. Look at https://github.com/dbt-labs/dbt-snowflake/pkgs/container/dbt-snowflake
2. 1.3.0 is tagged as latest.

### Environment

```markdown
- OS:
- Python:
- dbt-core:
- dbt-snowflake:
```

### Additional Context

This is related to https://github.com/dbt-labs/dbt-snowflake/issues/564

I posted a question in the discussions section on March 17 inquiring about this.

**Comment by dbeatty10** [comment]
Thanks for reaching out @scotthenley !

I'm not sure if this got fixed in the last couple hours, but [this](https://github.com/dbt-labs/dbt-snowflake/pkgs/container/dbt-snowflake) is showing 1.5.0 for me:

<img width="432" alt="image" src="https://user-images.githubusercontent.com/44704949/236929914-5e5ec20b-ba99-4ebf-8343-ca4a38520b68.png">


And so is [here](https://github.com/dbt-labs/dbt-snowflake):
<img width="253" alt="image" src="https://user-images.githubusercontent.com/44704949/236930092-da83ee56-3559-4028-ac66-7017b6cde58a.png">

Could you take a look again and see if this is fixed for you as well?

**Comment by scotthenley** [comment]
Hi @dbeatty10

I am still seeing the "latest" on the 1.3 image. We use the tag to pull the most recent version for various CI processes rather than bumping the version in our pipelines.

https://github.com/dbt-labs/dbt-snowflake/pkgs/container/dbt-snowflake/versions?filters%5Bversion_type%5D=tagged

![tag](https://github.com/dbt-labs/dbt-snowflake/assets/2483/ec4c02d9-3992-4f96-a6bf-1bca7d9b776f)

**Comment by gxpd-jjh** [comment]
@dbeatty10 It is still showing latest as v1.3.0.

**Comment by mikealfare** [comment]
From what we can tell, this tag is being deprecated and we cannot adjust it. Closing as "can't do".

**Comment by dbeatty10** [comment]
https://github.com/dbt-labs/dbt-core/pull/9495 fixes the underlying issue (thank you @mikealfare !), and this particular issue will be resolved for each 1.x version of this adapter upon its next patch release.

We are choosing not to address any [un-supported versions](https://docs.getdbt.com/docs/dbt-versions/upgrade-core-in-cloud#latest-releases) at this time, so <=1.4.x will **not** be updated.

Here are the most recent ones for the supported versions of dbt-snowflake in [PyPI](https://pypi.org/project/dbt-snowflake/#history):
- 1.7.1
- 1.6.6
- 1.5.6

So this will be completely resolved for >=1.5.x when each of the following are released (but only if each is released prior to falling out of support):
- 1.7.2
- 1.6.7
- 1.5.7

**Comment by dbeatty10** [comment]
Screenshot of `latest` and `1.7.latest`:

<img width="226" alt="image" src="https://github.com/dbt-labs/dbt-snowflake/assets/44704949/5fa80aa0-eae7-4af2-b55f-42ff990a721c">
